name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run install
        run: yarn install
      - name: Run build
        run: yarn build
      - name: Login to Packages Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        if: github['ref'] == 'refs/heads/main'
        run: |
          docker build --pull -f "build/Dockerfile" -t ghcr.io/siberianmh/turborepo-cache:latest .
          docker push ghcr.io/siberianmh/turborepo-cache:latest
